[package]
name = "rust-file-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
clap = { version = "4", features = ["derive"] }
aes-gcm = "0.10"
rand = "0.8"
hex = "0.4"
